### ISSUE TITLE
Custom low-level controller

### ISSUE THREAD

**Issue by SourabhPrasad** [moveit/moveit2#1524]
Hi, I am trying to develop the MoveIt2! pipeline for a custom manipulator. I would like to use a custom controller for my robot as ros2_control seems redundant as the motor driver has a control system built-in. So, all i need to do is send the trajectory generated by moveit to the micro-controller responsible for controlling the motor. I did read about FollowJointTrajectoryAction interface of moveit but I am confused on how to work with it. Is FollowJointTrajectoryAction interface the only way or is there any other method to send the trajectory.

I am using MoveIt2! with ROS Humble on Ubuntu 22.04

Please advice on how to implement it.
Any help is appreciated!
Thank you!

**Comment by metanav** [comment]
You would need an action server of type FollowJointTrajectoryAction to receive the goals. You can implement it on Ubuntu and send the commands to MCU over serial.

**Comment by Jason-Lee0** [comment]
Sorry to bother you guys, I have another problem. 

If I want to use moveit2 servo which using joystick to control the robot arm,  create the server of type FollowJointTrajectoryAction can also rechieve the work ?

- ROS2 version : Humble
- Ubuntu 22.04

Thanks for your reading.
Have a nice day!!

**Comment by AndyZe** [comment]
It's no problem @Jason-Lee0. An action server won't work for Servo. It's too slow to respond and the code isn't compatible with it anyway.

**Comment by Jason-Lee0** [comment]
@AndyZe Thanks for your quick reply.
An action server won't work for Servo, so how could I controll the real robot with moveit servo ? 

Could you give some advice to deal with it?

Thanks for your reading.
Sorry to bother you.

Best Regards.

**Comment by AndyZe** [comment]
First check if the driver of the robot is capable of streaming commands. Then make a controller that accepts std_msgs/Float64MultiArray or trajectory_msgs/JointTrajectory message types.

The standard way to do this is with ros2_control. Examples here:  https://github.com/ros-controls/ros2_control_demos

**Comment by mikeferguson** [comment]
This question appears to have been resolved by linking to appropriate demos
