### ISSUE TITLE
Consecutive planning_request_adapters can counteract each other

### ISSUE THREAD

**Issue by AndyZe** [moveit/moveit2#1604]
### Description

We almost always begin motion planning with these two planning request adapters:

  1. default_planner_request_adapters/FixStartStatePathConstraints
  2. default_planner_request_adapters/FixStartStateCollision
  
  They both "jiggle the start state" of the robot to get it back to a good state. This is just an observation that (2) can undo the effects of (1) so this strategy might not make sense.

**Comment by mikeferguson** [comment]
This is actually no longer an issue since the refactoring of the adapters - especially since the jiggle is gone
