### ISSUE TITLE
Replace the nullpointer checking in the Planning Scene with std::optional

### ISSUE THREAD

**Issue by AndyZe** [moveit/moveit2#2131]
Please ping @henningkayser or @tylerjw before starting this issue! It's just an idea.

Stuff like [this](https://github.com/ros-planning/moveit2/blob/acbf3770763e58e4f86ce0dea251a50cd4987fe6/moveit_core/planning_scene/include/moveit/planning_scene/planning_scene.h#L1035):

`std::unique_ptr<ObjectTypeMap> object_types_;`

```
  if (!object_types_)
  {
    ObjectTypeMap kc;
    parent_->getKnownObjectTypes(kc);
    object_types_ = ObjectTypeMap(kc);
  }
  else
  {
    ...
```

Ought to be replaced with std::optional<ObjectTypeMap>.

#2132 is a good start at this that seems like it could be extended for:

  scene_transforms_, robot_state_,  acm_, object_types_

**Comment by SuyashSapkal** [comment]
Hi @AndyZe , @tylerjw and @henningkayser 

I would like to work on this. Let me know what things I should be working on.

**Comment by AndyZe** [comment]
I think we need to at least wait for a review of #2132 first. If it's acceptable, you could apply the same techniques again.

Thanks @SuyashSapkal

**Comment by MEHARRAJ** [comment]
I would like to work on this. Let me know what things I should be working on.

**Comment by sjahr** [comment]
@MEHARRAJ Thank you, feel free to open a PR with the necessary changes

**Comment by zearocode** [comment]
Hi @AndyZe @tylerjw , I would like to work on this issue . May I know what changes should I do ?

**Comment by utkarshanand140** [comment]
Hey @AndyZe @tylerjw , has there been any progress on this ? If not, I would like to start work on this. Kindly lemme know.
