### ISSUE TITLE
Setup Assistant Crashes on Add Robot Poses

### ISSUE THREAD

**Issue by noahbuttner** [moveit/moveit2#2562]
### Description
I am attempting to use the setup assistant to create a MoveIt package for a custom URDF of our robot. However, it crashes when I go to add Robot Poses. I'm new to MoveIt, so if there's a better place to put this, please let me know.

### Your environment
* ROS Distro: Humble
* OS Version: e.g. Ubuntu 22.04
* Source or Binary build? Source
* If binary, which release version?
* If source, which branch? humble
* Which RMW (Fast DDS or Cyclone DDS)? Unsure, is there an easy way to check this?

### Steps to reproduce
Tell us how to reproduce this issue. Attempt to provide a working demo, perhaps using Docker.
My URDF is in the [gist](https://gist.github.com/noahbuttner/bccc751f34174af79dba611d20463610), and I can provide the meshes if needed.
- Launch the setup assistant in the above install types
- Use the provided URDF, and import it
- generate the collision matrix as default resolution
- create a base fixed virtual joint as in the tutorials
- create a planning group with all joints
- create a pose with KDL, and then move any of the joints in the robot pose generator.

### Expected behaviour
Setup assistant does not crash

### Actual behaviour
Setup assistant crashes when moving any joint in the robot pose window (see backtrace below).

### Backtrace or Console output

[bractrace](https://gist.github.com/noahbuttner/bccc751f34174af79dba611d20463610)

**Comment by mikeferguson** [comment]
Since this is a source build on humble - it is almost certainly the same issue as https://github.com/moveit/moveit2/issues/2980 - which appears to be an ABI issue due to differences in installed packages against the source. There's a lot more debugging notes available in the other ticket.
