### ISSUE TITLE
failed to call rcl_logging_rosout_add_sublogger!

### ISSUE THREAD

**Issue by Hadi-Hajieghrary** [moveit/moveit2#2659]
### Description

In move_group_interface.cpp after calling 

 robot_model_ = opt.robot_model ? opt.robot_model : getSharedRobotModel(node_, opt.robot_description);

, the node is changed - although it is passed as const, such that, calling node->get_logger().get_child("robot_planner") returns error:

failed to call rcl_logging_rosout_add_sublogger: The entry of logger 'robot_planner' not exist., at ./src/rcl/logging_rosout.c:438

This is in turn causes rclcpp_action::create_client to error out!

Overview of your issue here.

### Your environment
* ROS Distro: [iron]
* OS Version: e.g. Ubuntu 22.04
* Source or Binary build? Source
* If binary, which release version?
* If source, which branch? Iron
* Which RMW (Fast DDS or Cyclone DDS)? Humble or Rolling should be using Cyclone.

### Steps to reproduce
Tell us how to reproduce this issue. Attempt to provide a working demo, perhaps using Docker.

// Inisialize the ROS 2 Node
rclcpp::init(argc, argv);
rclcpp::NodeOptions node_options;
node_options.automatically_declare_parameters_from_overrides(true);
std::shared_ptr<rclcpp::Node> node = rclcpp::Node::make_shared("robot_planner", node_options);
MoveGroupInterface move_group(node, "panda_arm");

it returns the following error:

[robot_planner-1] terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
[robot_planner-1]   what():  failed to call rcl_logging_rosout_add_sublogger: The entry of logger 'robot_planner' not exist., at ./src/rcl/logging_rosout.c:438
[ERROR] [robot_planner-1]: process has died [pid 172667, exit code -6, cmd '/WorkSpace/mpb_ws/install/robot_planner/lib/robot_planner/robot_planner --ros-args -r __node:=robot_planner --params-file /tmp/launch_params_tvwu6dhe --params-file /tmp/launch_params_jnpa0d80 --params-file /tmp/launch_params_i23s1fzz --params-file /tmp/launch_params_d1y15mgt --params-file /tmp/launch_params_cpfc7ufx --params-file /tmp/launch_params_xljz6j67 --params-file /tmp/launch_params_27npgm3s --params-file /tmp/launch_params_pr00hn_y --params-file /tmp/launch_params_49vruo2v --params-file /tmp/launch_params_uuqaubou --params-file /tmp/launch_params_7_7tcrqr --params-file /tmp/launch_params_9g6awcrv --params-file /tmp/launch_params_3ryyird_ --params-file /tmp/launch_params_3pg9twc4 --params-file /tmp/launch_params_ajkd9_w7'].

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Backtrace or Console output

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

**Comment by henningkayser** [comment]
The description is a bit confusing to me.
Can you provide a link to point at the MGI code snippet that you think is broken? The node itself should not be changed or invalidated in a MGI instance.
