### ISSUE TITLE
Rviz is crashing on changing global fixed frame

### ISSUE THREAD

**Issue by tmachula** [moveit/moveit2#2661]
Hello hello, 

The issue very similar as https://github.com/ros-planning/moveit_resources/issues/170
Are there any news on it?

The difference for me is that I use a Universal Robot ur10e with an end effector.

Similarly, I can freely change the global frame for the panda robot when launching demo.launch.py of the pick and place tutorial.

A couple more hints:
1. I can change my rviz config for it to start with any other frame than the default "world" frame, it would start and use the frame without a problem. However, changing the frame when rviz is running results in a crash.
2. Possibly a related problem that has to do with frames: adding a TF visualization works fine. However, upon saving the configuration that has TF visualizations on and loading it again, rviz freezes.

Attached you can find my tf tree. 
![tf-frame](https://github.com/ros-planning/moveit_resources/assets/35599413/767e574a-b11d-472d-aaf3-589e3a798f5c)

What I tried so far is:
- removed the base frame that's not a part of the chain
- removed the end effector from the urdf

**Comment by henningkayser** [comment]
Can you provide more information like logs and screenshots of your RViz instance?
In particular, it would be interesting to know what plugins you have enabled, and which plugins produce the crash.

Please try only enabling the RobotModel display (with no MoveIt plugins enabled) and see if switching the global fixed frame does anything.
