### ISSUE TITLE
Remove topic name parameters in favor of const topic names

### ISSUE THREAD

**Issue by sjahr** [moveit/moveit2#2714]
In multiple places of moveit2 (for example [moveit_cpp](https://github.com/ros-planning/moveit2/blob/5887eb0e2eb8f6803d85fac458b11122fe495449/moveit_ros/planning/moveit_cpp/include/moveit/moveit_cpp/moveit_cpp.h#L65)), topic names can be configured with a parameter. This is not necessary because remapping topics on launch file level is trivial and the parameter API can be simplified by removing these parameters. Instead of having the topic names configurable with a ROS 2 parameters we should just use a const name in the cpp code.

**Comment by yash-011** [comment]
first issue was good

**Comment by Gaurang-1402** [comment]
Hi @sjahr  I have made a PR to the moveit2 repo that resolves this issue: https://github.com/ros-planning/moveit2/pull/2777

I'm curious to hear your feedback and improvise!
