### ISSUE TITLE
moveit_servo /servo_node/delta_twist_cmds only giving singularity errors 

### ISSUE THREAD

**Issue by PreetDhami** [moveit/moveit2#2760]
### Description
I'm trying to adapt moveit_servo to a custom robot arm as part of a university capstone project. I have managed to be able to successfully send `/servo_node/delta_joint_cmds` to control the arm, but `/servo_node/delta_twist_cmds` keeps giving singularity errors no matter the input.

### Your environment
* ROS Distro: Humble
* OS Version: e.g. Ubuntu 22.04

### Steps to reproduce
My source code is all located [here](https://github.com/PreetDhami/rover_arm_capstone_2024)
You should just be able to clone the code to a docker container, then build with colcon. To run, use:
```
ros2 launch rover_arm arm.launch.py
```
Then in a second terminal, publish a message such as this one below, but you can also play around with the values for the twist command:

```
ros2 topic pub --rate 10 --print 30 /servo_node/delta_twist_cmds geometry_msgs/msg/TwistStamped "{header: {frame_id: base_link, stamp: now}, twist: {linear: {x: 0.0, y: 0.0, z: -1.0}, angular: {x: 0.0, y: 0.0, z: 0.0}}}"
```

### Expected behaviour
`/servo_node` should publish some non-zero positions and velocitys to `/rover_arm_controller/joint_tragectory` when it receives a message on the `/servo_node/delta_twist_cmds` topic

### Actual behaviour
Any non-zero input for `/servo_node/delta_twist_cmds` leads to `/rover_arm_controller/joint_tragectory` recieving 'nan' values. Also I get the following warning messages:
![image](https://github.com/ros-planning/moveit2/assets/108783637/787b0c13-466e-4b77-8c96-5a2a94eaad06)

Whenever a topic is published to `/servo_node/delta_joint_cmds`, the code behaves as expected which can be checked by subscribing to the `/rover_arm_controller/joint_tragectory` topic. Publish a message such as this one to check:
```
ros2 topic pub --rate 10 --print 30 /servo_node/delta_joint_cmds control_msgs/msg/JointJog "{header: {frame_id: base_joint, stamp: now}, joint_names: [wrist_roll_joint], velocities: [1.0]}"
```

I believe that this is an issue with my config in some way. But I really don't know what the issue is.

**Comment by Flamethr0wer** [comment]
Hey @PreetDhami , did you manage to solve this?

**Comment by PreetDhami** [comment]
From what I remember, my issue was that the arm was starting right on the edge of it's range of motion. This was because my code started arm with all the joints at an angle of zero, so it was perfectly upright. 

What I did to fix it was adjust the starting positions of the joints so the arm is in a "ready" position, where all directional movement inputs are valid to make.

**Comment by Flamethr0wer** [comment]
@PreetDhami Oh okay, I actually managed to figure it out myself and in my case setting huge singularity thresholds and using `low_latency_mode: true` in the servo yaml file was the fix 👍
