### ISSUE TITLE
Load only 1 joint-model-group kinematics solver from the srdf

### ISSUE THREAD

**Issue by buckleytoby** [moveit/moveit2#2780]
My robot is composed of many move groups defined in the SRDF. I run different nodes for each of these move groups so I only need to load in the kinematics solver for that group specifically. However, the kinematics loader always loads all kinematics solvers, which is quite slow.

It doesn't make sense to split up the SRDF nor the URDF, as this is all one robot.

Is there a way to only load a single joint-model-group's kinematics solver?

**Comment by rhaschke** [comment]
> Is there a way to only load a single joint-model-group's kinematics solver?

No. The robot model will load all solvers for all groups.

> It doesn't make sense to split up the SRDF, as this is all one robot.

That's exactly the way to go, if you want to limit different nodes to some groups, I would say.
Consider using xacro to avoid duplication of SRDF code.
