### ISSUE TITLE
Trajectory end-point deviates too much from goal state error in panda moveit2 pick and place tutorial by picknik

### ISSUE THREAD

**Issue by Mustafaalam99** [moveit/moveit2#2794]
Hello,

I am running the panda moveit2 tutorial following the steps from [picknik pick and place tutorial.](https://moveit.picknik.ai/main/doc/tutorials/pick_and_place_with_moveit_task_constructor/pick_and_place_with_moveit_task_constructor.html). Once I run the demo files as mentioned at the end of the tutorial, I am getting the following error:

[mtc_tutorial-1] [WARN] [1713245752.503662871] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245752.559745649] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245752.614461012] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245752.670003269] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245752.757262220] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245752.812091905] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245752.867192145] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245752.923142824] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245752.978489650] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245753.041838231] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245753.097377855] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [INFO] [1713245753.129554237] [moveit.ompl_planning.model_based_planning_context]: Planner configuration 'panda_arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[mtc_tutorial-1] [WARN] [1713245753.208331470] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 3. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245753.282146098] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245753.349613241] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245753.404671918] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245753.514834878] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 3. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245753.569523856] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245753.624655776] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [INFO] [1713245753.638174224] [moveit.ompl_planning.model_based_planning_context]: Planner configuration 'panda_arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[mtc_tutorial-1] [WARN] [1713245753.729155802] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245753.815352272] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245753.878776528] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 3. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245753.933712285] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245753.989187053] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 3. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245754.044292019] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [INFO] [1713245754.130767508] [moveit.ompl_planning.model_based_planning_context]: Planner configuration 'panda_arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[mtc_tutorial-1] [WARN] [1713245754.198372905] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245754.254113234] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245754.310278832] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245754.364865600] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 3. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245754.420906049] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 3. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245754.476029444] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 3. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245754.553292227] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 3. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245754.608003600] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245754.672499404] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245754.737378655] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 3. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245754.792493844] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245754.848212286] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245754.905363509] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [INFO] [1713245754.949431821] [moveit.ompl_planning.model_based_planning_context]: Planner configuration 'panda_arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[mtc_tutorial-1] [WARN] [1713245755.018404003] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245755.074164078] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245755.129946973] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245755.185166179] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245755.250996878] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 3. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245755.306103327] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 3. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245755.377036655] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1] [WARN] [1713245755.431601120] [moveit_robot_state.cartesian_interpolator]: The computed trajectory is too short to detect jumps in joint-space Need at least 10 steps, only got 2. Try a lower max_step.
[mtc_tutorial-1]   0  - ←   0 →   -  0 / demo task
[mtc_tutorial-1]     1  - ←   1 →   -  0 / current
[mtc_tutorial-1]     -  0 →   1 →   -  1 / open hand
[mtc_tutorial-1]     -  1 →   0 ← 107  - / move to pick
[mtc_tutorial-1]   107  - ← 107 →   -107 / pick object
[mtc_tutorial-1]     107  - ← 107 ←   6  - / approach object
[mtc_tutorial-1]       6  - ← 130 →   -  6 / grasp pose IK
[mtc_tutorial-1]        25  - ←  25 →   - 25 / generate grasp pose
[mtc_tutorial-1]       -  6 → 124 →   -  0 / allow collision (hand,object)
[mtc_tutorial-1]       -  0 → 124 →   -  0 / close hand
[mtc_tutorial-1]       -  0 → 124 →   -  0 / attach object
[mtc_tutorial-1]       -  0 → 118 →   -118 / lift object
[mtc_tutorial-1]     -107 →   0 ← 488  - / move to place
[mtc_tutorial-1]   488  - ← 488 →   -  0 / place object
[mtc_tutorial-1]     1714  - ← 1714 →   -  0 / place pose IK
[mtc_tutorial-1]       1240  - ← 1240 →   -1240 / generate place pose
[mtc_tutorial-1]       -  0 → 1714 →   -  0 / open hand
[mtc_tutorial-1]       -  0 → 1714 →   -  0 / forbid collision (hand,object)
[mtc_tutorial-1]       -  0 → 1714 →   -  0 / detach object
[mtc_tutorial-1]       -  0 → 488 →   -488 / retreat
[mtc_tutorial-1]     -  0 → 478 →   -478 / return home
[mtc_tutorial-1] Failing stage(s):
[mtc_tutorial-1] move to pick (0/107): Trajectory end-point deviates too much from goal state
[mtc_tutorial-1] [ERROR] [1713245755.524014190] [mtc_tutorial]: Task planning failed

Can someone help me on this?

**Comment by rhaschke** [comment]
I guess you are running against MoveIt2's main branch. Try https://github.com/moveit/moveit_task_constructor/pull/542.
I'm not yet sure, why&where the main branch relaxed the goal reaching tolerance, which is the root cause of the problem.
