### ISSUE TITLE
How to disable looking for CHOMP planner

### ISSUE THREAD

**Issue by MannavaVivek** [moveit/moveit2#2845]
I am using ROS 2 Humble with the Robostack binaries on macOS, and MoveIt is attempting to load the CHOMP planner by default, which fails because the corresponding binaries are not yet available. While building CHOMP from source is an option, I would like to know how to configure MoveIt to avoid looking for the CHOMP planner, as the necessary YAML configuration files are provided in the source code and I can't modify those. I am following the MoveIt setup tutorials, and I have tried modifying the demo.launch.py file by specifying the pipelines using 
 `.planning_pipelines(pipelines=["ompl", "pilz_industrial_motion_planner"])` 
but MoveIt still tries to load the CHOMP planner and throws an error.

**Comment by sjahr** [comment]
I don't have any experience with Robostack binaries on macOS and we're not supporting that but using the .planning_pipelines parameter is the way to go. Are you sure you are not accidentally loading it somewhere else? If only chomp is loaded and others don't despite being explicitly parameterized could indicate an invalid  config. @MannavaVivek I'll close this issue for now, feel free to re-open if you still have any troubles and don't hesitate to copy&paste the log.
