### ISSUE TITLE
Jazzy Support and Release

### ISSUE THREAD

**Issue by henningkayser** [moveit/moveit2#2846]
[ROS 2 Jazzy is being released these days](https://docs.ros.org/en/jazzy/Releases/Release-Jazzy-Jalisco.html#release-timeline), and we are working on adding support for it in MoveIt, pushing for having the Source (and soon Debian) release version completed. The plan is to enable Noble CI jobs in all repositories, testing Jazzy along with Rolling, and applying the necessary remaining fixes. Thanks to @rhaschke a first step to fixing Noble support has been already provided with https://github.com/moveit/moveit2/pull/2793. The remaining steps for completion are:

- [x] Fix MoveIt docker images - new Jazzy and Rolling images are now available
- [x] Add Jazzy build job to MoveIt and dependencies https://github.com/moveit/moveit2/pull/2851
- [ ] Fix dependencies
    - [ ] Tutorials are failing, mainly because of a transitive dependency to the outdated gazebo-ros2-control package, see  https://github.com/Kinovarobotics/ros2_kortex/pull/159
    - [x] Octomap source build failed:  https://github.com/moveit/moveit2/actions/runs/9227203194/job/25388623434
           `CMake Error in CMakeLists.txt:
    IMPORTED_LOCATION or IMPORTED_IMPLIB not set for imported target "octomap"
    configuration "Debug".`
    - [x] Octomap ABI conflict: liboctomap-dev 1.9.7 (from fcl) and ros-*-octomap 1.10.0 (see https://github.com/moveit/moveit2/pull/2851#issuecomment-2132370683), continued in #2862
- [x] Release geometric_shapes: https://github.com/moveit/geometric_shapes/pull/242 
- [x] Release moveit_msgs: https://github.com/moveit/moveit_msgs/pull/178
- [x] Update build instructions on website
- [x] Cut release for Rolling and Jazzy - most binaries are already available in Jazzy, it's only blocked because of the failing moveit_ros_benchmarks build. https://github.com/moveit/moveit2/pull/2867

**Comment by rhaschke** [comment]
What fixes do you have in mind for the MoveIt docker images, @henningkayser?
With #2793, I thought I have fixed all open issues. I just noticed that - due to the ros-planning org migration, dockerhub doesn't yet receive image updates. That's tackled in #2847.

**Comment by henningkayser** [comment]
Jazzy: https://github.com/ros/rosdistro/pull/41645
Rolling: https://github.com/ros/rosdistro/pull/41643

**Comment by zouzhe1** [comment]
How long can we release Moveit2 that supports Noble versions? thanks   @henningkayser

**Comment by henningkayser** [comment]
Closing this, the broken tutorial issue is being tracked here https://github.com/moveit/moveit2/issues/2864

**Comment by usmanNoor5** [comment]
can i  install ubuntu 24.04 on jetson nano with ros2 jazzy with all that can i use isaac packages with it
