### ISSUE TITLE
CCov CI job failing in Rolling (Ubuntu Noble) - temporarily disabled

### ISSUE THREAD

**Issue by henningkayser** [moveit/moveit2#2866]
The ccov CI job has started showing [plenty of warnings and errors](https://github.com/moveit/moveit2/actions/runs/9481991275/job/26125918132?pr=2851) after migration to Noble. We need someone to dig into this and get it fixed.
Since CI is otherwise ok, I'm disabling ccov for now since unblocking releases and pull requests is higher priority.

**Comment by rhaschke** [comment]
I have seen some bug reports about this suggesting to downgrade lcov. I don't think this is an issue with our code.
