### ISSUE TITLE
Binary install is not working for jazzy

### ISSUE THREAD

**Issue by celuti** [moveit/moveit2#2893]
It is not possible to install MoveIt 2 from binary in Ubuntu 24.04 with ROS Jazzy: 
`sudo apt install ros-jazzy-moveit`
produces:
`Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package ros-jazzy-moveit`

**Comment by ukicomputers** [comment]
Try with this glob, on machine that has installed ROS 2 Jazzy:
`apt-get install -y "ros-jazzy-moveit-*" --no-install-recommends`

**Comment by sjahr** [comment]
The jazzy sync was delayed a bit: https://discourse.ros.org/t/preparing-for-jazzy-sync-and-patch-release-2024-06-28/38340. Does it work now?

**Comment by celuti** [comment]
> The jazzy sync was delayed a bit: https://discourse.ros.org/t/preparing-for-jazzy-sync-and-patch-release-2024-06-28/38340. Does it work now?

Still not, but I managed to install each subpackage individually as proposed @ukicomputers. Thank you!

**Comment by sea-bass** [comment]
Just tried

```
sudo apt list | grep ros-jazzy-moveit
```

and the packages are there now. Will go ahead and close it.
