### ISSUE TITLE
method for continuous plan&execute -> robot momentarily rush in an instant 

### ISSUE THREAD

**Issue by ahn1938549** [moveit/moveit2#2913]
I'm using a few manipulator 6-DOF. 

Problem is that I can't get velocities of these robots due to communication issues. 

So when controller success the goal before real goal pose due to goal tolerance then robot still moving to goal pose just little bit.

but when start next pose ahead, robot momentarily move to previous goal pose which planner thinks that is start pose.

strict goal tolerance can solve this problem but robot just stop when next plan time. so i'm not gonna do this things.

Solve this problem, 

1. Set start goal as a previous goal 

moveit::core::RobotState->setJointGroupPositions set this method for previous goal.

2. Using pipeline

Is there any other method to solve these problems? 

Thanks.

**Comment by mikeferguson** [comment]
This really sounds more like a configuration issue for your particular hardware - I think you'll have better luck asking on https://robotics.stackexchange.com/
