### ISSUE TITLE
Error building robotiq_driver

### ISSUE THREAD

**Issue by marlow-fawn** [moveit/moveit2#2919]
### Description

Trying to follow the tutorial for setting up moveit2 on humble. Ran into some issues building the robotiq packages - ignoring those packages results in a proper build. 

### Your environment
* ROS Distro: Humble
* OS Version: Ubuntu 22.04
* Binary build
* If binary, which release version?

### Steps to reproduce
Followed tutorial for [Getting Started](https://moveit.picknik.ai/main/doc/tutorials/getting_started/getting_started.html) up to colcon build.

### Expected behaviour
robotiq_driver package builds

### Actual behaviour
robotiq_driver package fails to build

### Backtrace or Console output

[Stack Trace](https://gist.github.com/marlow-fawn/37cbc0ade9a31fc1b5bcef05c3e8dde5)

**Comment by sea-bass** [comment]
The main branch of that repo is incompatible with Humble since this PR: https://github.com/PickNikRobotics/ros2_robotiq_gripper/pull/54

You will need to grab the `humble` branch instead and that should fix the error.

**Comment by sjahr** [comment]
Closing this as it looks like it is resolved
