### ISSUE TITLE
colcon build --mixin release failed

### ISSUE THREAD

**Issue by Helloxuxuxu** [moveit/moveit2#2926]
### Description

colcon build --mixin release failed

### Your environment
* ROS Distro:Humble
* OS Version:  Ubuntu 22.04
* source: the last source

### Actual behaviour
colcon build --mixin release

usage: colcon [-h] [--log-base LOG_BASE] [--log-level LOG_LEVEL]
              {build,extension-points,extensions,graph,info,list,metadata,mixin,test,test-result,version-check}
              ...
colcon: error: Mixin 'release' is not available for 'build'

**Comment by sjahr** [comment]
I guess you have not properly configured your mixin config. Take a look at https://github.com/colcon/colcon-mixin-repository. This is not a moveit issue so I am closing this issue. Please ask on https://robotics.stackexchange.com/ if you have further questions
