### ISSUE TITLE
Request for a new release of MoveIt into Rolling

### ISSUE THREAD

**Issue by clalancette** [moveit/moveit2#2928]
### Description

Following up on https://github.com/moveit/moveit2/pull/2881 , it would be great to get a new release of MoveIt into Rolling.  Once that is done, we'll be able to remove the octomap package from Rolling itself, and thus be able to close https://github.com/ros/rosdistro/issues/41622

### Your environment
* ROS Distro: Rolling
* OS Version: Ubuntu 24.04
* Binary
* New one, please :).
* Which RMW (Fast DDS or Cyclone DDS)? N/A

**Comment by clalancette** [comment]
Friendly ping here; this is the last remaining package before we can remove `octomap` from Rolling.

**Comment by clalancette** [comment]
Just as an FYI, I've now opened up https://github.com/ros/rosdistro/pull/42561 .  Once that is approved and merged, Moveit will no longer compile in Rolling until a new release is made.

**Comment by rhaschke** [comment]
@sjahr, @henningkayser: Is there any reason (except time constraints) that you didn't cut a new release yet?
If time is the only constraint, I can offer to create a new release.

**Comment by sjahr** [comment]
@rhaschke @clalancette Sorry I completely lost track of this and was out of office the past two weeks. Yes, at my end, time constraints are the only issue blocking this :see_no_evil: @rhaschke If you have the capacities to cut a new release, that would be awesome

**Comment by rhaschke** [comment]
Will do.

**Comment by rhaschke** [comment]
Release prepared: https://github.com/moveit/moveit2/pull/3002
But I'm lacking direct push permissions required by the release script.

**Comment by rhaschke** [comment]
Done: #3002
