### ISSUE TITLE
Need a gripper control in the realtime servoing

### ISSUE THREAD

**Issue by songhat** [moveit/moveit2#2932]
### Description

I can use the Xbox controller to freely control the end effector, but I can't control the closing of the gripper. How can I do this conveniently? In addition to using rviz to control

### Your environment
* ROS Distro: Humble
* OS Version: e.g. Ubuntu 22.04

**Comment by akky20** [comment]
@songhat can you please share more details like name of manipulator you are using and snippets of script for controlling gripper
