### ISSUE TITLE
typo "trajactory" in moveit_py

### ISSUE THREAD

**Issue by christian-rauch** [moveit/moveit2#2947]
### Description

There is a typo "traj**a**ctory" -> "traj**e**ctory" in `moveit_py`:
https://github.com/moveit/moveit2/blob/19d4a2818bca7024305cbf5be5c3bca4186351d5/moveit_py/src/moveit/moveit_ros/moveit_cpp/moveit_cpp.cpp#L174-L178

Unfortunately, fixing this typo will break API.

### Expected behaviour
The method should be named `get_trajectory_execution_manager`.

### Actual behaviour
The method is incorrectly named `get_trajactory_execution_manager`.

**Comment by sjahr** [comment]
@christian-rauch Thanks for reporting this. Would you mind opening a PR to fix it?

**Comment by akky20** [comment]
@sjahr I have raised a PR for this, can you please have a look into it

**Comment by JensVanhooydonck** [comment]
I guess there is still a typo in the pyi file: https://github.com/moveit/moveit2/blob/865ad364e1a8ae1582f9dfb8428eb4c152f3aa10/moveit_py/moveit/planning.pyi#L19
