### ISSUE TITLE
Change the starting point of planning under the plug-in using a topic or service

### ISSUE THREAD

**Issue by MrVBian** [moveit/moveit2#2972]
Hello Everyone,

I need to be able to change the starting point of planning under the MotionPlanning plugin via topic or service. But I don't know how to do it.

Any guidance on resolving this would be greatly appreciated.

Thank you.

**Comment by MrVBian** [comment]
Add a Topic Monitor picture:

![image](https://github.com/user-attachments/assets/ab1f3796-2893-4d60-8d27-ed351b18d5b4)

**Comment by sjahr** [comment]
Please take a look at the [tutorials](https://moveit.picknik.ai/main/index.html), especially the ones around the move_group interface. For future questions on how to use moveit, please use https://robotics.stackexchange.com/

**Comment by MrVBian** [comment]
> Please take a look at the [tutorials](https://moveit.picknik.ai/main/index.html), especially the ones around the move_group interface. For future questions on how to use moveit, please use https://robotics.stackexchange.com/

Thank you for your reply. @sjahr 

Sorry, after reading the document, I still can't figure out how to change the starting point of the plan through topic or service. Can you give me some more Pointers. For example, which topic or service should I study. 

Thanks again for your reply.

**Comment by MrVBian** [comment]
[https://robotics.stackexchange.com/](https://robotics.stackexchange.com/questions/112648/how-to-change-the-starting-point-of-planning-under-the-plug-in-using-a-topic-or). This question was also asked

**Comment by sjahr** [comment]
The [MotionPlanRequest has a field called start_state](https://github.com/moveit/moveit_msgs/blob/9756797dcbc293c7cae66541a7bc0c7acec85892/msg/MotionPlanRequest.msg#L10) you can use to set the start state. The motion plan request can be set either with the move_group interface or moveit_cpp

**Comment by MrVBian** [comment]
I think you misunderstood my question.
- The setStartState function in move_group_interface cannot modify the start attitude in rviz. The same cannot be said for MotionPlanRequest.
- What I need is not a custom start point and end point, and then solve a trajectory.

What I need is how to change the green Query start state under the moveit plugin after rviz is started.

![image](https://github.com/user-attachments/assets/9ec837ba-561e-4649-8398-de6e9c582b21)

**Comment by rhaschke** [comment]
To enable external control of the rviz MotionPlanning plugin, you need to tick the corresponding checkbox first:
![image](https://github.com/user-attachments/assets/46050a9c-ca00-4526-9bf5-aa9bd28dedc5)

Then, you can send start / goal states to the topics `/rviz/moveit/update_custom_start_state` and `/rviz/moveit/update_custom_goal_state`. 
The topics `/rviz/moveit/update_start_state` and `/rviz/moveit/update_goal_state`, accepting an empty message, reset the corresponding state to the current one.

**Comment by MrVBian** [comment]
Thank you for your reply, which answered my question. @rhaschke
