### ISSUE TITLE
Pressing backspace on the first page of the MoveIt Setup Assistant crashes the application

### ISSUE THREAD

**Issue by EzraBrooks** [moveit/moveit2#2982]
### Description

Pressing backspace on the first page of the MoveIt Setup Assistant crashes the application

### Your environment
* ROS Distro: Humble
* OS Version: Ubuntu 22.04
* Source or Binary build? Source
* If source, which branch? approx. main
* Which RMW (Fast DDS or Cyclone DDS)? Cyclone.

### Steps to reproduce
Press backspace in the MSA outside of a text field.

### Expected behaviour
no-op

### Actual behaviour
It crashes.

### Backtrace or Console output

Seems to fail silently? Or it's getting swallowed in my environment.

**Comment by mikeferguson** [comment]
I am unable to reproduce this using latest Humble
