### ISSUE TITLE
 No kinematics plugins defined. Fill and load kinematics.yaml!

### ISSUE THREAD

**Issue by PedroMoreo** [moveit/moveit2#2983]
### Description

My name is Pedro, working for the University of Granada lab.
We are trying to move a Universal Robot arm and we want to move it through URSIM beforehand. To do this we are trying to adapt the hello_moveit_ur project (configured for panda) https://moveit.picknik.ai/humble/doc/tutorials/your_first_project/your_first_project.html to ur5e or ur3e.

In this project they explain how to make a launch file for this purpose: https://github.com/LucaBross/simple_moveit2_universal_robots_movement/blob/main/README.md 
But I cannot make it works

### Your environment
* ROS Distro: Humble
* OS Version:  Ubuntu 22.04
* Source or Binary build?
* I am using a binary version of moveit_config and a binary version of ur_robot_driver
* If binary, which release version?
* If source, which branch?
* Which RMW (Fast DDS or Cyclone DDS)? Humble or Rolling should be using Cyclone.

### Steps to reproduce
According to the README provided for Luca Bross in the same github mentioned before:

Shell 1: run the driver
`ros2 launch ur_robot_driver ur_control.launch.py ur_type:=ur3e robot_ip:=172.17.0.2 launch_rviz:=false initial_joint_controller:=joint_trajectory_controller to connect to the Universal Robot.`

Start the external control urcap on the UR to allow external control (172.17.0.2 )
whose answer is :
```
[ur_ros2_control_node-1] [INFO] [1724836702.880117247] [UR_Client_Library:]: Robot requested program
[ur_ros2_control_node-1] [INFO] [1724836702.880196920] [UR_Client_Library:]: Sent program to robot
[ur_ros2_control_node-1] [INFO] [1724836702.909041735] [UR_Client_Library:]: Robot connected to reverse interface. Ready to receive control commands.
```

Shell 2: run the moveit controller
```
ros2 launch ur_moveit_config ur_moveit.launch.py ur_type:=ur3e launch_rviz:=true 
to cofigure moveit.
```
whose anser is :
```
[rviz2-2] [INFO] [1724836802.044574767] [interactive_marker_display_95582728855616]: Sending request for interactive markers
[rviz2-2] [INFO] [1724836802.078529470] [interactive_marker_display_95582728855616]: Service response received for initialization
[rviz2-2] [INFO] [1724836862.032627211] [move_group_interface]: Ready to take commands for planning group ur_manipulator.
```

Shell 3: launch the program hello
Start the hello_moveit_ur file with a launchfile 
`ros2 launch hello_moveit_ur hello_moveit_ur_launch.py.`
whose anser is:
```
[INFO] [launch]: All log files can be found below /home/pedro/.ros/log/2024-08-28-11-36-43-385497-pedro-B650-AORUS-ELITE-AX-11823
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [hello_moveit_ur-1]: process started with pid [11826]
[hello_moveit_ur-1] [INFO] [1724837803.703205261] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.00261015 seconds
[hello_moveit_ur-1] [INFO] [1724837803.703235167] [moveit_robot_model.robot_model]: Loading robot model 'ur'...
[hello_moveit_ur-1] [INFO] [1724837803.703242611] [moveit_robot_model.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
[hello_moveit_ur-1] [WARN] [1724837803.770902047] [moveit_ros.robot_model_loader]: No kinematics plugins defined. Fill and load kinematics.yaml!

```

### Expected behaviour
The robot to move in the UR SIM, to the selected point.

### Actual behaviour
It gives a warning about the kinematics and keep waiting.

Thanks a lot.

**Comment by sea-bass** [comment]
As the log message suggests, did you create a `kinematics.yaml` file? See here as an example https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/main/ur_moveit_config/config/kinematics.yaml

The Setup Assistant does not automate this part, to the best of my knowledge.

**Comment by rhaschke** [comment]
> The Setup Assistant does not automate this part, to the best of my knowledge.

It does. I think you are missing the kinematics parameter config in your `hello_moveit_ur_launch.py` launch file.
See [`ur_moveit.launch.py`](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/main/ur_moveit_config/launch/ur_moveit.launch.py#L174) for an example.

**Comment by sea-bass** [comment]
Thanks for the correction. I guess the best of my knowledge didn't have much "best" to it 🤣

**Comment by rhaschke** [comment]
I think you managed to load the kinematics parameters now, although you didn't follow the suggested example, which is much simpler. I cannot help much with the remaining issue, as I have no idea about the purpose of `hello_moveit_ur`. I suggest adding some prints to understand where the program hangs.

**Comment by PedroMoreo** [comment]
Hi
Sorry, I think I was not very clear in the previous explanation of the problem.
I don't have much experience in ROS2 yet.

I was just following this tutorial https://moveit.picknik.ai/humble/doc/tutorials/your_first_project/your_first_project.html (hello_moveit). The purpose is just to move the robot to a point. This tutorial is configured for PANDA. I need to change it for ur5e (ur3e would work too). But I couldn't change it. This tutorial just runs a file(using run command), it does not use a launch file ( [example.launch.py](http://example.launch.py/)).

According to this forum https://answers.ros.org/question/408096/using-universal-robot-instead-of-pandas-arm-in-moveit2-tutorial/ (it is the same question here https://forum.universal-robots.com/t/move-ur-with-a-moveit2-script/24497)
the solution needs to be done through a launch file. The complete files are in : [GitHub - LucaBross/simple_moveit2_universal_robots_movement ](https://github.com/LucaBross/simple_moveit2_universal_robot) But I couldn't run this project.
So this is the problem I have, looks like I am trying the regular examples, but for some reason I can't make it work.
I hope this helps.

Thanks a lot.

**Comment by nachoorp** [comment]
Hello @PedroMoreo, just started my master thesis and trying to do exactly the same here in the UPM, did you managed to move the robot into a desired point? Im quite new to ros so any info can be helpful, thanks in advance!

**Comment by PedroMoreo** [comment]
Hello @nachoorp , yes we did, but for the moment we have errors in the orientation. You can follow all the steps I did in the next link

[https://forum.universal-robots.com/t/no-kinematics-plugins-defined-fill-and-load-kinematics-yaml/35834/4 ]

I hope it helps
