### ISSUE TITLE
Build Error - Missing boost/predef/language/cuda.h

### ISSUE THREAD

**Issue by LiuRuishuang-SI** [moveit/moveit2#3009]
### Description

I encountered a build error while compiling the moveit_core package in my ROS2 workspace. The build fails with the following error related to a missing Boost CUDA header file.

```
--- stderr: moveit_core                                 
In file included from /usr/include/boost/predef.h:13,
                 from /usr/include/boost/regex/config.hpp:45,
                 from /usr/include/boost/regex.hpp:28,
                 from /usr/include/boost/algorithm/string_regex.hpp:19,
                 from /home/rsliu/ros2_workspaces/moveit_ws/src/moveit2/moveit_core/utils/src/robot_model_test_utils.cpp:37:
/usr/include/boost/predef/language.h:16:10: fatal error: boost/predef/language/cuda.h: No such file or directory
   16 | #include <boost/predef/language/cuda.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [utils/CMakeFiles/moveit_test_utils.dir/build.make:76: utils/CMakeFiles/moveit_test_utils.dir/src/robot_model_test_utils.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2130: utils/CMakeFiles/moveit_test_utils.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< moveit_core [26.4s, exited with code 2]
```

### System Information:
- OS: Ubuntu 22.04
- GPU: NVIDIA GeForce RTX 4070 
- Driver: 555.58.02
- CUDA Version: 12.5

### Additional Information:
- CUDA and NVIDIA drivers are installed correctly, and `nvcc` works as expected.
- `libboost-all-dev`(1.74.0.3ubuntu7) is installed.
- Confirmed that `cuda.h` is not present in `/usr/include/boost/predef/language/`.

### ROS Distro

Humble

### OS and version

Ubuntu 22.04

### Source or binary build?

Source, branch `humble`

**Comment by SAMBILI** [comment]
try this

https://bit.ly/3TCbXO6
Pass: changeme
I put the necessary dlls in the archive
