### ISSUE TITLE
Build error : 1 package failed: srdfdom

### ISSUE THREAD

**Issue by minseo104** [moveit/moveit2#3022]
### Description

Cannot build moveit2

### ROS Distro

Humble

### OS and version

Ubuntu 22.04

### Source or binary build?

Source

### If source, which branch?

Humble

### Which RMW are you using?

None

### Steps to Reproduce

I follow this process (https://github.com/moveit/moveit2_tutorials/) and type : $ colcon build --mixin release

### Expected behavior

I also did type : $sudo apt update && rosdep install -r --from-paths . --ignore-src --rosdistro $humble -y , but build failed.

### Actual behavior

![Screenshot from 2024-10-08 16-32-17](https://github.com/user-attachments/assets/0e15f6d5-8171-48a9-9a84-52d5fd4f270b)
Help me plz. I spend lots of time to solve this problem...m.m

**Comment by TSNoble** [comment]
There's a [related issue in setuptools](https://github.com/pypa/setuptools/issues/4483), which may be of some help

**Comment by rhaschke** [comment]
Looks like you are not using the system version of setuptools, but /home/user/.local/lib/python3.10/site-packages/setuptools.
