### ISSUE TITLE
Several OMPL interface tests started failing with `humble_ci` job on main

### ISSUE THREAD

**Issue by sea-bass** [moveit/moveit2#3130]
### Description

This only started a few days ago (w.r.t. the issue creation date):
https://github.com/moveit/moveit2/actions/runs/11988362896/job/33423544280

This is unique to the `humble_ci` job on the `main` branch -- we need to either pinpoint and fix the cause of failure, or draw the line to say building that the `main` branch from source no longer works on Humble.

I'd like to see if we can figure out the issue first, and only resort to the latter option if absolutely necessary.

### ROS Distro

Humble

### OS and version

Ubuntu 22.04

### Source or binary build?

Source

### Which RMW are you using?

None

### Steps to Reproduce

https://github.com/moveit/moveit2/actions/runs/11988362896/job/33423544280

### Expected behavior

Tests should pass

### Actual behavior

Tests do not pass

**Comment by rr-tom-noble** [comment]
Related to https://github.com/moveit/moveit2/issues/1952

It seems to be geometric_shapes throwing the error. Specifically, [these lines](https://github.com/moveit/geometric_shapes/blob/c24eb4940646b4584f8961c75e4807a44637e3d7/src/bodies.cpp#L603-L604)

**Comment by sea-bass** [comment]
Ah! Yeah, turns out there was a commit to `geometric_shapes` that landed 5 days ago: https://github.com/moveit/geometric_shapes/pull/239

And this repo is actually building it from source.

I've attempted to pin the SHA of this dependency in https://github.com/moveit/moveit2/pull/3132 to see if this is it...

**Comment by sea-bass** [comment]
Found the issue. https://github.com/moveit/geometric_shapes/pull/252 should fix it.
