### ISSUE TITLE
MoveIt installation broken

### ISSUE THREAD

**Issue by PietroValerio** [moveit/moveit2#3152]
### Description

If you follow the steps provided with moveit2 [tutorials](https://moveit.picknik.ai/main/doc/tutorials/getting_started/getting_started.html) inside jazzy, when you arrive to the step `sudo apt update && rosdep install -r --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y` all releated packages are not installed so you cant install from source neither from binary as referred in https://moveit.ai/install-moveit2/binary/

### ROS Distro

Jazzy

### OS and version

Ubuntu 24.04

### Source or binary build?

Source

### If source, which branch?

main

### Which RMW are you using?

None

### Steps to Reproduce

follow all the steps as provided in https://moveit.picknik.ai/main/doc/tutorials/getting_started/getting_started.html

### Expected behavior

working out of the box

### Actual behavior

Not working

### Backtrace or Console output

ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install -y ros-jazzy-joint-state-publisher] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-joint-state-publisher-gui] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-xacro] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-controller-manager] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-picknik-reset-fault-controller] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-picknik-twist-controller] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-geometric-shapes] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-launch-pytest] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-rmf-utils] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-ros2-control] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-warehouse-ros-sqlite] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-gz-ros2-control] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-joint-trajectory-controller] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-position-controllers] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-generate-parameter-library] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-srdfdom] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-ros-testing] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-py-binding-tools] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-gripper-controllers] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-joint-state-broadcaster] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-launch-param-builder] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-control-msgs] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-realtime-tools] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-octomap-msgs] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-warehouse-ros] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-ompl] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-controller-manager-msgs] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-ros2-controllers] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-google-benchmark-vendor] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-osqp-vendor] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-rsl] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-ruckig] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-ament-cmake-google-benchmark] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-hardware-interface] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-object-recognition-msgs] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-ament-clang-format] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-ament-clang-tidy] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-graph-msgs] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-topic-tools] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-backward-ros] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-ros-gz-bridge] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-ros-gz-sim] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-stomp] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-controller-interface] failed
  apt: command [sudo -H apt-get install -y ros-jazzy-tl-expected] failed
  apt: Failed to detect successful installation of [ros-jazzy-joint-state-publisher]
  apt: Failed to detect successful installation of [ros-jazzy-joint-state-publisher-gui]
  apt: Failed to detect successful installation of [ros-jazzy-xacro]
  apt: Failed to detect successful installation of [ros-jazzy-controller-manager]
  apt: Failed to detect successful installation of [ros-jazzy-picknik-reset-fault-controller]
  apt: Failed to detect successful installation of [ros-jazzy-picknik-twist-controller]
  apt: Failed to detect successful installation of [ros-jazzy-geometric-shapes]
  apt: Failed to detect successful installation of [ros-jazzy-launch-pytest]
  apt: Failed to detect successful installation of [ros-jazzy-rmf-utils]
  apt: Failed to detect successful installation of [ros-jazzy-ros2-control]
  apt: Failed to detect successful installation of [ros-jazzy-warehouse-ros-sqlite]
  apt: Failed to detect successful installation of [ros-jazzy-gz-ros2-control]
  apt: Failed to detect successful installation of [ros-jazzy-joint-trajectory-controller]
  apt: Failed to detect successful installation of [ros-jazzy-position-controllers]
  apt: Failed to detect successful installation of [ros-jazzy-generate-parameter-library]
  apt: Failed to detect successful installation of [ros-jazzy-srdfdom]
  apt: Failed to detect successful installation of [ros-jazzy-ros-testing]
  apt: Failed to detect successful installation of [ros-jazzy-py-binding-tools]
  apt: Failed to detect successful installation of [ros-jazzy-gripper-controllers]
  apt: Failed to detect successful installation of [ros-jazzy-joint-state-broadcaster]
  apt: Failed to detect successful installation of [ros-jazzy-launch-param-builder]
  apt: Failed to detect successful installation of [ros-jazzy-control-msgs]
  apt: Failed to detect successful installation of [ros-jazzy-realtime-tools]
  apt: Failed to detect successful installation of [ros-jazzy-octomap-msgs]
  apt: Failed to detect successful installation of [ros-jazzy-warehouse-ros]
  apt: Failed to detect successful installation of [ros-jazzy-ompl]
  apt: Failed to detect successful installation of [ros-jazzy-controller-manager-msgs]
  apt: Failed to detect successful installation of [ros-jazzy-ros2-controllers]
  apt: Failed to detect successful installation of [ros-jazzy-google-benchmark-vendor]
  apt: Failed to detect successful installation of [ros-jazzy-osqp-vendor]
  apt: Failed to detect successful installation of [ros-jazzy-rsl]
  apt: Failed to detect successful installation of [ros-jazzy-ruckig]
  apt: Failed to detect successful installation of [ros-jazzy-ament-cmake-google-benchmark]
  apt: Failed to detect successful installation of [ros-jazzy-hardware-interface]
  apt: Failed to detect successful installation of [ros-jazzy-object-recognition-msgs]
  apt: Failed to detect successful installation of [ros-jazzy-ament-clang-format]
  apt: Failed to detect successful installation of [ros-jazzy-ament-clang-tidy]
  apt: Failed to detect successful installation of [ros-jazzy-graph-msgs]
  apt: Failed to detect successful installation of [ros-jazzy-topic-tools]
  apt: Failed to detect successful installation of [ros-jazzy-backward-ros]
  apt: Failed to detect successful installation of [ros-jazzy-ros-gz-bridge]
  apt: Failed to detect successful installation of [ros-jazzy-ros-gz-sim]
  apt: Failed to detect successful installation of [ros-jazzy-stomp]
  apt: Failed to detect successful installation of [ros-jazzy-controller-interface]
  apt: Failed to detect successful installation of [ros-jazzy-tl-expected]

**Comment by sea-bass** [comment]
Did you run these steps?

```
sudo rosdep init
rosdep update
sudo apt update
sudo apt dist-upgrade
